import NavbarPage from "./components/navbar";
import "./globals.css";
import { Plus_Jakarta_Sans } from "next/font/google";

const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-white ${jakarta.className} h-[4000px]`}>
        <NavbarPage />
        {children}
      </body>
    </html>
  );
}
